---
title: "Valid-Tab_v1"
author: "Eric-Alexandre Coudry"
date: "4 juin 2018"
output: pdf_document
---

```{r setup, include=FALSE}
library(knitr)
library(kableExtra)
library(dplyr)
library(lubridate)
library(eeptools)
library(tidyr)

fipa <- readRDS('K:/Data/2015-2016/PA24/FIPA_PA24.rds')

options(scipen = 999, digits = 2)
```

# FIPA_PA24

```{r results='asis'}

fipa_1 <- fipa %>% 
 mutate(DatNaiss = as.Date(DatNaiss),
        age = age_calc(DatNaiss, 
                      enddate = as.Date('2015-04-01'), 
                      units = "years", precise = F)) %>%
  arrange(BenBanls,Sexe) %>%
 
   mutate(Groupe = if_else(age >= 60 & age <= 70,"[60,70[",
                           if_else(age >= 71 & age <= 80, "[71,80[",
                                   if_else(age >= 81 & age <= 90, "[81,90[",
                                           if_else(age >= 91 & age <= 100, "[91,100[", "[100 et +["))))) %>%
  
count(Groupe, Sexe) %>%
  
  spread(Sexe, 3) %>%
  
  arrange(match(Groupe,c("[60,70[","[71,80[","[81,90[","[91,100[","[100 et +["))) %>%
  
  select(Groupe, Hommes = M, Femmes = F)  %>%
  
  mutate(Total = Femmes + Hommes)




totFIPA <- list(
  Hommes = sum(fipa_1$Hommes),
  Femmes = sum(fipa_1$Femmes),
  Total = sum(fipa_1$Total)
)

tot_fi <- c("Total",
            totFIPA[["Hommes"]],
            totFIPA[["Femmes"]],
            totFIPA[["total"]])
  
fipa_1 <- rbind(fipa_1, tot_fi)


fipa_1 <- fipa_1 %>%
  
mutate(Hommes = as.numeric(Hommes),
       Femmes = as.numeric(Femmes),
       Total = as.numeric(Total)) %>%
  
  mutate(Hommes = paste0(Hommes," (",Hommes / totFIPA_h * 100,"%)"),
         Femmes = paste0(Femmes," (",Femmes / totFIPA_F * 100,"%)"))
         # Total = paste0(Total," (",Total / totFIPA_T * 100,"%)"))
         
         
         
  kable(fipa_1, "latex") %>%       
  kable_styling(latex_options = "striped") %>%
  add_header_above(c("","Sexe" = 2, ""))

```
